//
//  Persistence.swift
//  BunqInterviewApp
//
//  Created by Charel Felten on 23/08/2022.
//

import CoreData

struct PersistenceController {
    // this class is mostly auto-generated by SwiftUI when chosing to
    // develop a CoreData app
    
    static let shared = PersistenceController()

    static var preview: PersistenceController = {
        let result = PersistenceController(inMemory: true)
        let viewContext = result.container.viewContext
        let testPayment = Payment(context: viewContext)
        testPayment.recipient = "TEST"
        testPayment.value = 99.99
        testPayment.timestamp = Date()
        do {
            try viewContext.save()
        } catch {
            let nsError = error as NSError
            fatalError("Unresolved error \(nsError), \(nsError.userInfo)")
        }
        return result
    }()

    let container: NSPersistentContainer

    init(inMemory: Bool = false) {
        container = NSPersistentContainer(name: "BunqInterviewApp")
        if inMemory {
            container.persistentStoreDescriptions.first!.url = URL(fileURLWithPath: "/dev/null")
        }
        container.loadPersistentStores(completionHandler: { (storeDescription, error) in
            if let error = error as NSError? {
                fatalError("Unresolved error \(error), \(error.userInfo)")
            }
        })
        container.viewContext.automaticallyMergesChangesFromParent = true
    }
}
